# Generated by Django 4.2.7 on 2023-11-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumb',
            field=models.ImageField(null=True, upload_to='thumbnails'),
        ),
    ]
