# Generated by Django 4.2.7 on 2023-11-29 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_topic_alter_blog_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='topicname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogs.topic'),
        ),
    ]
