# Generated by Django 4.2.7 on 2023-12-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_blog_topicname'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.TextField(default='admin'),
        ),
    ]
